name: Reusable Cherry Pick to PR

on:
  workflow_call:
    inputs:
      commit_sha:
        required: true
        type: string
      target_branch:
        required: true
        type: string
      origin_pr_url: # 1. NOUVEL INPUT ICI
        required: false
        type: string
        default: ''

jobs:
  cherry-pick-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configuration de Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Création de la branche et Cherry-pick
        id: cp
        run: |
          SHORT_SHA=$(echo "${{ inputs.commit_sha }}" | cut -c1-7)
          NEW_BRANCH="cherry-pick-${SHORT_SHA}-to-${{ inputs.target_branch }}-${{ github.run_id }}"
          echo "branch_name=$NEW_BRANCH" >> $GITHUB_OUTPUT

          git checkout ${{ inputs.target_branch }}
          git checkout -b $NEW_BRANCH

          git cherry-pick -m 1 ${{ inputs.commit_sha }} || (git cherry-pick --abort && echo "Conflit détecté, annulation." && exit 1)
          git push origin $NEW_BRANCH --force

      - name: Création de la Pull Request
        env:
          GH_TOKEN: ${{ secrets.PAT_CHERRY_PICK || github.token }} 
          ORIGIN_PR_URL: ${{ inputs.origin_pr_url }} # 2. ON PASSE L'INPUT EN VARIABLE ENV
        run: |
          PR_EXISTS=$(gh pr list --head "${{ steps.cp.outputs.branch_name }}" --base "${{ inputs.target_branch }}" --json url --jq '.[0].url')
          
          # 3. CONSTRUCTION DE LA DESCRIPTION DYNAMIQUE
          PR_BODY="Ce PR a été généré automatiquement suite au merge du commit \`${{ inputs.commit_sha }}\`."
          if [ -n "$ORIGIN_PR_URL" ]; then
            PR_BODY="$PR_BODY"$'\n\n'"🔗 **PR d'origine :** $ORIGIN_PR_URL"
          fi

          if [ -z "$PR_EXISTS" ]; then
            gh pr create \
              --base "${{ inputs.target_branch }}" \
              --head "${{ steps.cp.outputs.branch_name }}" \
              --title "🍒 Cherry-pick: commit ${{ inputs.commit_sha }} vers ${{ inputs.target_branch }}" \
              --body "$PR_BODY"
          else
            echo "La Pull Request existe déjà et a été mise à jour par le push --force : $PR_EXISTS"
          fi